In [7]:
import json
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
caseFrame = pd.read_json('../caseData_all.json')

In [9]:
caseFrame.head()

,title,tid,court,date,judge,full_text,resolution,dressMentioned
0,Madan Gopal Kakkad vs Naval Dubey And Anr on 2...,1314858,Supreme Court of India,1992-04-29,"Bench: Pandian, S.R. (J)",CRIMINAL APPELLATE JURISDICTION : Criminal App...,\n\nConviction,\n\nNo
1,Santhosh Madhavan @ Amrutha ... vs Circle Insp...,1815206,Kerala High Court,2008-07-21,unknown,A girl aged 14 years is the alleged victim in ...,\n\nNeither,\n\nYes
2,Atender Yadav vs State Govt Of Nct Of Delhi on...,151172763,Delhi High Court,2013-10-29,Author: Kailash Gambhir,"KAILASH GAMBHIR, J. 1. By this appeal filed un...",\n\nacquittal,\n\nNo
3,"Beeru vs State Nct Of Delhi on 11 December, 2013",13922091,Delhi High Court,2013-12-11,Author: Kailash Gambhir,"% KAILASH GAMBHIR, J. 1. One can visibly see t...",\n\nAcquittal,\n\nNo
4,"State Of Haryana vs Anil Kumar on 11 July, 2003",1076070,Punjab-Haryana High Court,2003-07-11,"Bench: S Nijjar, S Grewal","JUDGMENT S.S. Nijjar, J. 1. The State of Harya...",\n\nConviction,\n\nYes

In [21]:
caseFrame['dressMentioned'].unique()

array(['No', 'Yes',
       "The complainant's clothes were mentioned in the case.",
       "The prosecutrix's dress came up in the case.", ' yes',
       'The appellant herein faced prosecution before the Court of Session, Kasaragod (Special Court for the trial of offences against women and children) on a charge under Section 376 (1) IPC, and under Section 5 read with Section 6 of the Protection of Children from Sexual Offences (POCSO)Act',
       'The Hon\'ble Apex Court observed as follows: "It is not in dispute that the condition precedent to the applicability of Section 302 of the IPC is that the act must be done with intent to dishonour or disfigure the victim. It has been held by this Court in several cases that mere exposure',
       '"The State failed to adduce any evidence to prove that the case does not satisfy condition nos.3 and 4. In one of the recent decisions of the Hon\'ble Apex Court in Dattatraya @ Datta Ambo Rokade .vs. State of Maharashtra , reported in 2020',
       '"The Court noted with interest the submissions of the learned counsel for the appellant that in cases of sexual offences, the clothes worn by the victim may be important evidence. It was held that while it is for the prosecution to adduce evidence to show that the case does not satisfy condition no.3, it is',
       'Maybe',
       'The clothes mentioned in the case are those of the victim, Sheela Devi.',
       'maybe', 'No.',
       "The victim's clothes were not mentioned in the case.", 'Yes.',
       'The clothes mentioned in the case are black.',
       "The victim's clothes were mentioned in the case.",
       'The clothes mentioned in the case are those of the victim.',
       "The victim's dress or clothes may have come up in the case.",
       'Both these appeals are directed against the judgment and order dated 21/11/2016, passed by the Sessions Judge, Nanded in Sessions Case No.4/2015. The appellants herein have been convicted for the offences punishable under Section 376(D) (gang rape), Section 354(A) (1',
       'Manju Dutta: No',
       "The clothes mentioned in the case were the victim's dress.",
       '- In the case of Suresh Kumar Das v. State of West Bengal, the Supreme Court observed that "In a case of sexual offence, conviction can be recorded on the sole basis of the testimony of the prosecutrix, provided her testimony is found to be reliable and free from any infirmity. On',
       '"At one point of time, the appellant had torn the clothes of the prosecutrix and when she objected to it, he slapped her. There is no evidence to suggest that the appellant tore the clothes of the prosecutrix with an intention to outrage her modesty."No',
       "Blood was detected on exhibits '3' and '4'.",
       'Sher Alam ran away from the spot while cleaning his penis with a cloth.',
       'Bangsani color salwar, multicolour suit green dupatta, and hawai chappal in her feet.',
       "The victim's dress or clothes came up in the case.",
       "The clothes mentioned in the case are the victim's dress and underwear.",
       ' No',
       "The victim's daughter was not found and her clothes were not mentioned in the case.",
       ' Yes', "The victim's dress was mentioned in the case.",
       "The victim's dress was not mentioned in the case.",
       'The clothes mentioned in the case are the clothing of the child victim.',
       "The victim's dress or clothes were not mentioned in the case.",
       'No.16381 of 2013 -3-C.W.P. No.17102 of 2013 -4-',
       'In Writ Petition (C) No. 10 of 2013, Salil Bali Vs. Union of India, Writ Petition (C) No. 85 of 2013, Krishna Deo Prasad Vs. Union of India, Writ Petition (C) No. 42 of 2013, Kamal Kumar Pandey & Suk',
       '"It was also pointed out by the learned counsel for the State that though in a criminal trial the prosecution is not required to prove beyond reasonable doubt that the accused was wearing a particular article of clothing at the time of the commission of the offence, still it is incumbent on them to adduce such evidence which',
       "1) a bruise over the back of the victim's scalp2) meninges and brain were congested over a petechial hemorrhage3) multiple bruises over the neck and windpipe area, as well as on the mucus membrane surrounding the eyes and nose4) bruises on the upper",
       '-Disabled women struggle with both the oppression of being women in male dominated societies and the oppression of being disabled in societies dominated by the able-bodied.Yes',
       '"In the present case, the appellant had promised to marry the prosecutrix. But he did not keep his promise and instead married another girl. The prosecutrix claimed that she was misled by the appellant and that she did not know about his other marriage. The Court held that it was not necessary for the prosecution to',
       '-A cotton swab marked 12-A torn green colour netted frock with polyester lining and pink color lace with dirty stains marked 3-A torn yellow color mill made underwear with dirty stains 4-A torn blue and light brown color checks design cotton bed sheet with dark brown stains-A',
       'The clothes mentioned in the case are not explicitly mentioned, but it can be assumed that they may have come up in the case.',
       "The Medical Board's opinion mentions that the victim's dress came up in the case.",
       "-Arya's school uniform-Arya's pajama-Arya's undergarments",
       '1. A black shirt2. Jeans3. White T-shirt4. Brown shoes',
       "The victim's daughter was wearing a sprinkled pink and blue dress, with chappals in her feet.",
       "-The victim's dress came up in the case.",
       " prosecutrix's mother stated that it was a matter of chedchad with prosecutrix",
       'The facts in brief of the prosecution case are that on 23.3.2009, _________x_____W/o ______y____ R/o __________________, herein after referred to as the prosecutrix, lodged a report at P.S. New Ashok Nagar, alleging that she was',
       "The victim's daughter Latika told her that accused put his penis in her vagina, due to which she felt pain.",
       "The victim's dress or clothes mentioned in the case are not explicitly stated.",
       'T\xadshirt',
       "The victim's shirt and pants were opened and she found bleeding from her genital.",
       'The case of the prosecution, as reflected in the chargesheet, is that on 23.01.2013, the prosecutrix (her name is withheld to protect her identity) came to the police station Nand Nagri, Delhi and filed a complaint against the accused. In her complaint, the prosecutrix stated',
       'The case of prosecution is that on 17.01.2012 the prosecutrix (name is withheld to protect her identity) went out of her house for her tuition class but did not come back. A missing complaint was lodged at police station Harsh Vihar vide DD No. 39 B dated 17.01.',
       'The case of the prosecution as reflected in the chargesheet is that on 04.05.2013 the prosecutrix (her name is withheld to protect her identity) came to police station Pandav Nagar and lodged a complaint (Ex.PW1/A) against accused Alam Khan. In her complaint,',
       '"The word \'modesty\' has been defined by the Supreme Court in Tarkeshwar Sahu ....vs. State of Bihar (2006) 8 SCC 560 as follows: "Modesty is the quality or state of being modest. It implies a sense of propriety and decency, and includes not',
       "The appellant's clothes were mentioned in the case.",
       'No.24/1, 1st Cross, Kausar Nagar, R.T.Nagar Post, Bengaluru - 560 032.',
       'No. of the case & Date of institution :16/2 (2009)/(1998)Date of commission of offence :20\xad09\xad1998Name of the complainant :State through Ms. Suman NimName of the accused :Prem Giri Goswami S/o Lt. R',
       "No.2's conclusion is that the victim's dress or clothes came up in the case.",
       'No. of the case C.C.No.5840/2020 Date of commission of the From 07.11.2018 to 2.',
       'Lungi and shirt', 'None',
       'In Criminal Misc. Case No.3447/2009, the petitioner has sought quashing of the proceedings arising from FIR No.826/2007 which was initially registered u/s 304-B/498-A of IPC and in which the petitioners were discharged of the offence u/s 304',
       'No. 12 of 2020 - Sri Bhanjoy Tripura was convicted of murdering his father.',
       'The mother has filed the said O.P. seeking permanent custody of her minor twin children and to appoint herself as the guardian of the person of the twin minor children.',
       ' no',
       'Both the petitions were heard together and the order is passed as a common order. For the sake of conveniency, Criminal Miscellaneous Application No.7510 of 2020 is treated as the lead matter.',
       '1. Koka Rai @ Dinesh Rai Son Of Late Budhu Rai R/O Village-Bakarpur, P.S.- Rajapakar, District-Vaishali2. Ranjit Rai Son Of Late Singeshwar Rai R/O Village-Bakarpur,',
       'In both Criminal Appeals Criminal Appeals filed under Section 374(2) Cr.P.C., praying to set aside the judgment of conviction and sentence, dated 22.01.2013, passed by the Sessions Judge, Mahila Court, Salem, in S.C.No.67 of 2010. These Criminal',
       'The clothes mentioned in the case may or may not come up in the case.',
       ' The petitioner was convicted for the offences punishable under Sections 323, 324, 342, 354, 504 and 506 of the Indian Penal Code, 1860.',
       'Gray chaddar type shawl',
       ' prosecutrix stated that Sunil had taken out his private part from his underwear and entered it in her vagina despite her refusal.',
       'both appeals', 'The cloth mentioned was a coarse cloth.'],
      dtype=object)

In [20]:
caseFrame = caseFrame.replace('\n','', regex=True)
caseFrame.head()

,title,tid,court,date,judge,full_text,resolution,dressMentioned
0,Madan Gopal Kakkad vs Naval Dubey And Anr on 2...,1314858,Supreme Court of India,1992-04-29,"Bench: Pandian, S.R. (J)",CRIMINAL APPELLATE JURISDICTION : Criminal App...,Conviction,No
1,Santhosh Madhavan @ Amrutha ... vs Circle Insp...,1815206,Kerala High Court,2008-07-21,unknown,A girl aged 14 years is the alleged victim in ...,Neither,Yes
2,Atender Yadav vs State Govt Of Nct Of Delhi on...,151172763,Delhi High Court,2013-10-29,Author: Kailash Gambhir,"KAILASH GAMBHIR, J. 1. By this appeal filed un...",acquittal,No
3,"Beeru vs State Nct Of Delhi on 11 December, 2013",13922091,Delhi High Court,2013-12-11,Author: Kailash Gambhir,"% KAILASH GAMBHIR, J. 1. One can visibly see t...",Acquittal,No
4,"State Of Haryana vs Anil Kumar on 11 July, 2003",1076070,Punjab-Haryana High Court,2003-07-11,"Bench: S Nijjar, S Grewal","JUDGMENT S.S. Nijjar, J. 1. The State of Harya...",Conviction,Yes

In [23]:
resultCode = []
dressCode = []
for index, row in caseFrame.iterrows():
    if('neither' in row['resolution'].lower()):
        resultCode.append("U")
    elif('acquit' in row['resolution'].lower()):
        resultCode.append("A")
    elif('convict' in row['resolution'].lower()):
        resultCode.append("C")
    elif('dismiss' in row['resolution'].lower()):
        resultCode.append("A")
    else:
        resultCode.append("U")
    
    if(row['dressMentioned'].strip().lower() in ['yes', 'yes.']):
        dressCode.append("Y")
    elif(row['dressMentioned'].strip().lower() in ['no', 'no.']):
        dressCode.append("N")
    elif(row['dressMentioned'].strip().lower() in ['maybe', 'maybe.']):
        dressCode.append("M")
    elif('not mentioned' in row['dressMentioned'].lower()):
        dressCode.append("N")
    elif('mentioned' in row['dressMentioned'].lower()):
        dressCode.append("Y")
    elif('came up' in row['dressMentioned'].lower()):
        dressCode.append("Y")
    elif('not come up' in row['dressMentioned'].lower()):
        dressCode.append("N")
    elif('come up' in row['dressMentioned'].lower()):
        dressCode.append("Y")
    else:
        dressCode.append("M")

caseFrame['resultCode'] = resultCode
caseFrame['dressCode'] = dressCode

In [24]:
caseFrame.head(50)

,title,tid,court,date,judge,full_text,resolution,dressMentioned,resultCode,dressCode
0,Madan Gopal Kakkad vs Naval Dubey And Anr on 2...,1314858,Supreme Court of India,1992-04-29,"Bench: Pandian, S.R. (J)",CRIMINAL APPELLATE JURISDICTION : Criminal App...,Conviction,No,C,N
1,Santhosh Madhavan @ Amrutha ... vs Circle Insp...,1815206,Kerala High Court,2008-07-21,unknown,A girl aged 14 years is the alleged victim in ...,Neither,Yes,U,Y
2,Atender Yadav vs State Govt Of Nct Of Delhi on...,151172763,Delhi High Court,2013-10-29,Author: Kailash Gambhir,"KAILASH GAMBHIR, J. 1. By this appeal filed un...",acquittal,No,A,N
3,"Beeru vs State Nct Of Delhi on 11 December, 2013",13922091,Delhi High Court,2013-12-11,Author: Kailash Gambhir,"% KAILASH GAMBHIR, J. 1. One can visibly see t...",Acquittal,No,A,N
4,"State Of Haryana vs Anil Kumar on 11 July, 2003",1076070,Punjab-Haryana High Court,2003-07-11,"Bench: S Nijjar, S Grewal","JUDGMENT S.S. Nijjar, J. 1. The State of Harya...",Conviction,Yes,C,Y
5,State Of Maharashtra vs Haresh Mohandas Rajput...,1867349,Bombay High Court,2008-01-11,"Bench: S Radhakrishnan, R Dalvi","JUDGMENT S. Radhakrishnan, J. Page 0378 1. By ...",Conviction,Yes,C,Y
6,Lokesh Mishra vs State Of Nct Of Delhi on 12 M...,173157344,Delhi High Court,2014-03-12,Author: Kailash Gambhir,"KAILASH GAMBHIR, J. 1. The present appeal has ...",Conviction,Yes,C,Y
7,State Of Karnataka By The Kadur ... vs Revanna...,1537204,Karnataka High Court,2005-02-25,"Bench: S Bannurmath, A Kabbin","JUDGMENT A.C. Kabbin, J. 1. The main point for...",Acquittal,No,A,N
8,Sugam @ Monty Harishankar Jaiswal vs Opponent(...,96325177,Gujarat High Court,2012-12-27,unknown,Whether Reporters of Local Papers may be allow...,Conviction,Yes,C,Y
9,"A.O. Thomas vs State on 1 January, 2009",710630,Kerala High Court,2009-01-01,unknown,The sole accused in S.C.No.58/99 on the file o...,Acquittal,No,A,N
10,Hari Shankar Tewari vs State Of Tripura on 3 J...,193132,Gauhati High Court,2005-06-03,"Bench: R Misra, A Pal","JUDGMENT A.B. Pal, J. 1. These two appeals are...",Conviction,Yes,C,Y
11,K.Muthu Mariappan : vs The State Rep By The In...,13522556,Madras High Court,2015-06-12,unknown,************* The appellant is the sole accuse...,Conviction,Yes,C,Y
12,Mr. J.S. Choudhary vs Mr. Mahesh Bora on 12 Ap...,83475160,Rajasthan High Court - Jodhpur,2014-04-12,unknown,Hon'ble the Supreme Court in Rajveer@Raju and ...,Neither,Yes,U,Y
13,Sant Shri Asharam Bapu vs State on 10 February...,150890944,Rajasthan High Court - Jodhpur,2014-02-10,unknown,[1] 14 IN THE HIGH COURT OF JUDICATURE FOR RAJ...,Neither,No,U,N
14,Sc No.122/2013: Fir No.146/2013: ... vs Sundar...,13255571,Delhi District Court,2015-05-01,Author: Sh. Vinod Yadav,BRIEF FACTS OF THE CASE: The facts of the cas...,Conviction,No,C,N
15,"State vs . Mohd. Zahid on 9 October, 2013",159019789,Delhi District Court,2013-10-09,Author: Sh. Pawan Jain,Briefly stated facts of prosecution case are t...,Conviction,The complainant's clothes were mentioned in th...,C,Y
16,"Briefly Stated The Case Of ... vs . on 24 May,...",105300006,Delhi District Court,2014-05-24,Author: Sh. Bharat Parashar,1. Briefly stated the case of prosecution as u...,Conviction,The prosecutrix's dress came up in the case.,C,Y
17,"State vs Raman Kumar on 20 July, 2015",44516798,Delhi District Court,2015-07-20,Author: Sh. Vikas Dhull,1. The prosecution story in brief is that on r...,Conviction,Yes,C,Y
18,Fir No. 148/13 : State vs Sunil @ Machhar : Ps...,105505244,Delhi District Court,2015-05-08,Author: Sh. Vinod Yadav,Facts of the case The facts of the case as bor...,Conviction,Yes,C,Y
19,Shatrughna Baban Meshram vs The State Of Mahar...,17904216,Supreme Court of India,2020-11-02,"Bench: Uday Umesh Lalit, Vineet Saran, S. Ravi...","Uday Umesh Lalit, J. 1. These appeals by Spec...",Conviction,Yes,C,Y
20,Independent Thought vs Union Of India on 11 Oc...,87705010,Supreme Court of India,2017-10-11,Bench: D Gupta,"Madan B. Lokur, J. 1. The issue before us is l...",Neither,No,U,N
21,Ms. Eera Through Dr. Manjula ... vs State (Gov...,69624144,Supreme Court of India,2017-07-21,Bench: [ Misra],"R.F.NARIMAN, J. (concurring) 1. Having read th...",Neither,No,U,N
22,"Manoharan vs State By Inspector Of Police, ......",29644710,Supreme Court of India,2019-08-01,"Bench: Rohinton Fali Nariman, Sanjiv Khanna, S...","R.F. NARIMAN, J. 1. Leave granted. 2. The pr...",Conviction.,Yes,C,Y
23,Patan Jamal Vali vs The State Of Andhra Prades...,138189653,Supreme Court of India,2021-04-27,"Bench: Hon'Ble Dr. Chandrachud, M.R. Shah","Dr Dhananjaya Y Chandrachud, J This judgment h...",The resolution is a conviction.,Yes,C,Y
24,Attorney General For India vs Satish on 18 Nov...,123392914,Supreme Court of India,2021-11-18,"Bench: Uday Umesh Lalit, S. Ravindra Bhat, Hon...","BELA M. TRIVEDI, J. 1. Leave granted in all a...",The resolution is a conviction.,No,C,N
25,Aparna Bhat vs The State Of Madhya Pradesh on ...,13024806,Supreme Court of India,2021-03-18,"Bench: A.M. Khanwilkar, S. Ravindra Bhat","S. RAVINDRA BHAT, J. A woman cannot be herself...",Neither,No,U,N
26,Hemudan Nanbha Gadhvi vs The State Of Gujarat ...,171003922,Supreme Court of India,2018-09-28,Author: J Navin Sinha,"NAVIN SINHA, J. The appellant assails his conv...",Conviction,yes,C,Y
27,Nawabbudin vs State Of Uttarakhand on 8 Februa...,171601131,Supreme Court of India,2022-02-08,"Bench: M.R. Shah, B.V. Nagarathna","M. R. Shah, J. 1. Feeling aggrieved and dissa...",Conviction,Yes,C,Y
28,Friday vs Manoj Kumar,130148481,Kerala High Court,1800-01-01,unknown,"necessities of life. Guru imparts knowledge, m...",Conviction,Yes,C,Y
29,Hem Lal Sah vs The State Of Bihar on 11 Februa...,13048856,Patna High Court,2014-02-11,unknown,"judgment, dated 01.10.2013, passed, in Session...",conviction,Yes,C,Y
30,"State Of Bihar vs Hemlal Sah on 11 February, 2014",167495904,Patna High Court,2014-02-11,unknown,"judgment, dated 01.10.2013, passed, in Session...",Conviction,Yes,C,Y
31,"Asif vs State Of U.P. on 4 August, 2015",127519888,Allahabad High Court,2015-08-04,"Bench: Surendra Vikram Rathore, Raghvendra Kumar","Hon'ble Raghvendra Kumar,J. (Per Raghvendra Ku...",Conviction,Yes,C,Y
32,Crime No.503/2014 Of Kumbla ... vs By Adv. Sri...,130619722,Kerala High Court,2015-09-08,unknown,The appellant herein faced prosecution before ...,Neither,No,U,N
33,"Javed vs State on 21 February, 2013",60208089,Delhi High Court,2013-02-21,Author: Pratibha Rani,"1. The complainant, in this case, is mother of...",Conviction,No,C,N
34,Crime No.503/2014 Of Kumbla ... vs By Adv. Sri...,140100528,Kerala High Court,2015-09-08,unknown,The appellant herein faced prosecution before ...,Conviction,The appellant herein faced prosecution before ...,C,M
35,Ram Bilas @ Basawan Son Of Shri Ram ... vs Sta...,33668975,Punjab-Haryana High Court,2013-09-20,unknown,"Present: Mr. Jasdev Singh Mehndiratta, Advocat...",Conviction,Yes,C,Y
36,Vikas Kumar Meskar vs Union Of India & Ors on ...,68960214,Punjab-Haryana High Court,2014-12-10,unknown,This writ petition is directed against the ord...,Conviction,Yes,C,Y
37,"Somar Nat vs State Of Bihar & Anr on 1 April, ...",192514666,Patna High Court - Orders,2014-04-01,unknown,2 01-04-2014 The present application has been ...,Neither,No,U,N
38,Sabhajeet Maurya vs State Nct Of Delhi on 26 N...,24721411,Delhi High Court,2020-11-26,unknown,"VIBHU BAKHRU, J Introduction 1. The appellant ...",The resolution is an acquittal.,No,A,N
39,"Raghav vs State on 24 May, 2018",99332745,Delhi High Court,2018-05-24,unknown,"1. This appeal, at the instance of the appella...",Conviction,Yes,C,Y
40,The State Of Mah. Thr. Pso Ps ... vs Sagar Vis...,37952890,Bombay High Court,2021-09-07,"Bench: V.M. Deshpande, Amit B. Borkar","Judgment reserved on : AUGUST 05, 2021. Judgme...",Neither,"The Hon'ble Apex Court observed as follows: ""I...",U,M
41,"Ram Pal vs State Of U.P. on 7 November, 2017",21089980,Allahabad High Court,2017-11-07,Bench: Virendra Kumar-Ii,"1. Heard Mr. Arjun Kumar 'Kaushal', learned co...",Conviction.,Yes,C,Y
42,Nikhil S/O Shivaji Golait vs State Of Mah. Thr...,71101333,Bombay High Court,2021-09-07,"Bench: V.M. Deshpande, Amit B. Borkar","Judgment reserved on : AUGUST 05, 2021. Judgme...",Neither,"""The State failed to adduce any evidence to pr...",U,M
43,Sagar Vishwanath Borkar vs State Of Maharashtr...,173322176,Bombay High Court,2021-09-07,"Bench: V.M. Deshpande, Amit B. Borkar","Judgment reserved on : AUGUST 05, 2021. Judgme...",Neither,"""The Court noted with interest the submissions...",U,M
44,"Vikram Khimta vs State Of H.P on 1 November, 2018",134421600,Himachal Pradesh High Court,2018-11-01,Bench: Honourable Mr. Sharma,Instant criminal appeal filed under Section 37...,Acquittal,No,A,N
45,Anil Surendrasingh Yadav vs State Of Gujarat o...,137212109,Gujarat High Court,2019-12-27,"Bench: Bela M. Trivedi, A.C. Rao",1 Whether Reporters of Local Papers may be all...,Conviction,No,C,N
46,Vishnu Madan Gore vs The State Of Maharashtra ...,135013234,Bombay High Court,2021-02-11,"Bench: Ravindra V. Ghuge, B. U. Debadwar","SG Punde, PA ::: Uploaded on - 24/02/2021 ::: ...",Conviction,No,C,N
47,The State Of Maharashtra vs Vishnu S/O. Madan ...,17746051,Bombay High Court,2021-02-11,"Bench: Ravindra V. Ghuge, B. U. Debadwar","SG Punde, PA ::: Uploaded on - 24/02/2021 ::: ...",Conviction,No,C,N
48,The State Of Maharashtra vs Mohammad Aabed Moh...,172501724,Bombay High Court,2022-02-08,"Bench: S.S. Jadhav, P. K. Chavan",The stone of a grave had crushed the candle be...,Conviction.,Maybe,C,M
49,Suresh Chand And Ors vs State Of H.P. And Ors ...,195814010,Himachal Pradesh High Court,2020-08-31,Bench: Sandeep Sharma,By way of instant petition filed under Section...,Acquittal,No,A,N

In [30]:
print("Convicted: ", len(caseFrame[caseFrame['resultCode'] == 'C']))
print("Acquitted: ", len(caseFrame[caseFrame['resultCode'] == 'A']))
print("Unknown: ", len(caseFrame[caseFrame['resultCode'] == 'U']))

Convicted:  2725
Acquitted:  1314
Unknown:  1269

In [31]:
print("Clothes Mentioned: ", len(caseFrame[caseFrame['dressCode'] == 'Y']))
print("Clothes Not Mentioned: ", len(caseFrame[caseFrame['dressCode'] == 'N']))
print("Clothes Maybe Mentioned: ", len(caseFrame[caseFrame['dressCode'] == 'M']))

Clothes Mentioned:  2360
Clothes Not Mentioned:  2689
Clothes Maybe Mentioned:  259